services:
  client:
    build: .
    container_name: wheresmybus-client
    restart: always
    environment:
      - TZ=Australia/Brisbane
      - API_BASE_URL=http://wheresmybus-api:3000/api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - wmb-net

networks:
  wmb-net:
    external: true