services:
  api:
    build: .
    container_name: wheresmybus-api
    restart: always
    environment:
      - PORT=${PORT}
      - RT_UPDATE_INTERVAL_MS=${RT_UPDATE_INTERVAL_MS}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - wmb-net

networks:
  wmb-net:
    external: true